### ISSUE TITLE
P18.串行化 例子有小问题

### ISSUE THREAD

**Issue by anhanx** [dromara/transaction-book#11]
第一步中，应该和前面几个例子一样是 “select * from account；”吧？不需要where条件，因为后面是 “可以看到，张三，李四和王五……”，看到的是三个人的账户信息。

或者后面就改成 “可以看到，张三的账户余额为300元”，是不是会好一些。

**Comment by binghe001** [comment]
> 



> 第一步中，应该和前面几个例子一样是 “select * from account；”吧？不需要where条件，因为后面是 “可以看到，张三，李四和王五……”，看到的是三个人的账户信息。
> 
> 或者后面就改成 “可以看到，张三的账户余额为300元”，是不是会好一些。

感谢反馈，这个已经在加印版本中修正了
