### ISSUE TITLE
p19 书写错误

### ISSUE THREAD

**Issue by shafishcn** [dromara/transaction-book#16]
![p19](https://user-images.githubusercontent.com/22794651/156989398-bea4e0a7-b7bd-4812-84d7-318a3d37a1db.jpg)

文字第四行横线那里应该是`在串行的事务隔离级别下`

**Comment by yu199195** [comment]
感谢你的提醒

**Comment by shafishcn** [comment]
> 感谢你的提醒

或者是按书里原来的意思：在可重复事务隔离下，事务范围查询后，并行事务不能在该范围内插入新数据？可以讲一下`在某范围内插入数据`具体如何操作吗，感谢

**Comment by shafishcn** [comment]
不好意思，看到后面p22提到的间隙锁，确实是事务范围操作后，并行事务不能插入或修改，书中p19那里木有写错。
