### ISSUE TITLE
9.3.3　Confirm阶段流程  描述有误

### ISSUE THREAD

**Issue by Jon-Gaara** [dromara/transaction-book#17]
如果Try阶段的业务逻辑全部执行成功，则TCC分布式事务会执行Confirm阶段的业务逻辑。在实际场景中，Confirm阶段的执行往往是由TCC分布式事务框架调用完成的。在订单服务中会将订单的状态由“支付中”更新为“支付成功”。**在库存服务中会真正地扣减库存，将写入冻结字段的库存数量减去当次下单时提交的商品数量**。在积分服务中会将当次支付产生的积分从预增加积分字段中扣除，并将对应的积分增加到用户积分账户中。在仓储服务中会将出库单的状态由“未知”更新为“已创建”.
   
  1.在Try阶段就已经把当次下单时提交的商品数量写入冻结字段，然后又用冻结字段的库存数量减去当次下单提交的商品数量，不就是等于0了么？
 2.Try阶段的第二步，已经将商品库存数量减去冻结的商品数量，为什么在Confirm阶段还要去减？我的理解是在Confirm阶段，库存服务只要删除冻结的库存数量就好了或者解冻冻结的库存数量
3.在Confirm阶段的第二步，预扣减字段中的库存数量减去当次下单提交的商品数量，不一样还是0么？应该是库存数量减去预扣减字段中的库存数量把

**Comment by yu199195** [comment]
假设有3个字段

|  库存总数  | 冻结数量  |可用数量   | 
|  ----  | ----  |----  |
| 100  | 0| 100 |

执行 try后 变更成：

|  库存总数  | 冻结数量  |可用数量   | 
|  ----  | ----  |----  |
| 99  | 1| 99 |

try没有异常那么执行confirm，把冻结的数量扣除
|  库存总数  | 冻结数量  |可用数量   | 
|  ----  | ----  |----  |
| 99  | 1-1 = 0| 99 |

Try执行后，如果其他服务有异常，需要回滚，则把冻结数量 加回去

|  库存总数  | 冻结数量  |可用数量   | 
|  ----  | ----  |----  |
| 99+1 = 100  | 1-1 = 0| 99 +1 = 100 |

**Comment by Jon-Gaara** [comment]
谢谢，明白了
