### ISSUE TITLE
10.2.1 实现原理  图文不符合

### ISSUE THREAD

**Issue by Jon-Gaara** [dromara/transaction-book#18]
你好，图10-2 我感觉画的有点问题，图中显示事务参与方如果一直执行不成功，会修改消息状态，而文字描述的是事务参与方如果仍然发送不成功，则会给事务发起方发送一条事务执行失败的消息，图文描述不符合，而且在第二步，事务发起方成功发送消息的时候就已经删除了消息，应该是没办法修改消息状态的，而且事务参与方也应该是没办法去修改事务发起方数据库的本地消息表的吧

**Comment by binghe001** [comment]
> 你好，图10-2 我感觉画的有点问题，图中显示事务参与方如果一直执行不成功，会修改消息状态，而文字描述的是事务参与方如果仍然发送不成功，则会给事务发起方发送一条事务执行失败的消息，图文描述不符合，而且在第二步，事务发起方成功发送消息的时候就已经删除了消息，应该是没办法修改消息状态的，而且事务参与方也应该是没办法去修改事务发起方数据库的本地消息表的吧

感谢反馈，图示确实存在问题，后续会根据表述修正图示
