### ISSUE TITLE
p32 图片的描述信息有误？

### ISSUE THREAD

**Issue by midnight2104** [dromara/transaction-book#2]
图2-3 原图中的描述：
每秒写入`OS Buffer`并调用   `fsyncI()`   函数刷盘

应该是 ` fsyncI()   ->  fsync()   ?`

**Comment by binghe001** [comment]
> 
> 
> 图2-3 原图中的描述： 每秒写入`OS Buffer`并调用 `fsyncI()` 函数刷盘
> 
> 应该是 ` fsyncI() -> fsync() ?`

是的，原稿是fsync()，印刷错误，已记录更正，感谢反馈

**Comment by binghe001** [comment]
> 
> 
> 图2-3 原图中的描述： 每秒写入`OS Buffer`并调用 `fsyncI()` 函数刷盘
> 
> 应该是 ` fsyncI() -> fsync() ?`

谢谢反馈，加印版已经更正
