### ISSUE TITLE
P89 4.2.4 SOA架构，关于分布式架构缺点表述

### ISSUE THREAD

**Issue by origin-meta** [dromara/transaction-book#20]
当部署的服务越来越多是，**重复的代码就会变得越来越多。** 
请问分布式架构不是抽取公共的服务，以提高代码复用性，4.2.3中也提及相关优点，但在4.2.4处表述就成了缺点？

**Comment by binghe001** [comment]
> 当部署的服务越来越多是，**重复的代码就会变得越来越多。** 请问分布式架构不是抽取公共的服务，以提高代码复用性，4.2.3中也提及相关优点，但在4.2.4处表述就成了缺点？

这个前后并不矛盾，你可以好好体会下，4.2.3是从代码复用的角度说的，4.2.4是从服务依赖，如果出现问题造成的后果方面说的
