### ISSUE TITLE
p47 图片中描述信息是否有误？

### ISSUE THREAD

**Issue by midnight2104** [dromara/transaction-book#3]
图2-11 MySQL事务执行流程

步骤2. 查询数据表中待更新的数据到内存，并加涣

并加涣 ？？？

**Comment by binghe001** [comment]
感谢反馈  原稿是并加锁，印刷错误了，已通知出版社更正

**Comment by binghe001** [comment]
> 
> 
> 图2-11 MySQL事务执行流程
> 
> 步骤2. 查询数据表中待更新的数据到内存，并加涣
> 
> 并加涣 ？？？

感谢反馈 原稿是并加锁，印刷错误了，已通知出版社更正

**Comment by binghe001** [comment]
> 
> 
> 图2-11 MySQL事务执行流程
> 
> 步骤2. 查询数据表中待更新的数据到内存，并加涣
> 
> 并加涣 ？？？


谢谢反馈，加印版已经更正
