### ISSUE TITLE
p82_1.4.MySQL事务基础_4.串行化 sql语句结果和文字描述结果不一致

### ISSUE THREAD

**Issue by Murphys-uestc** [dromara/transaction-book#4]
mysql> select * from account where id = 1; 
上述语句执行，应该只返回一条张三的数据，而文中描述“可以看到，张三、李四和王五的账户余额分别为300元、350元和500元”，表达出语句返回了三个人的数据

**Comment by binghe001** [comment]
> 
> 
> mysql> select * from account where id = 1; 上述语句执行，应该只返回一条张三的数据，而文中描述“可以看到，张三、李四和王五的账户余额分别为300元、350元和500元”，表达出语句返回了三个人的数据

感谢反馈，这里应该是 可以看到，张三的账户余额为300。  排版时印刷错误了，感谢反馈

**Comment by binghe001** [comment]
> 
> 
> mysql> select * from account where id = 1; 上述语句执行，应该只返回一条张三的数据，而文中描述“可以看到，张三、李四和王五的账户余额分别为300元、350元和500元”，表达出语句返回了三个人的数据


谢谢反馈，加印版已经更正
