### ISSUE TITLE
p105_6.3.4 2pc模型存在的一致性问题

### ISSUE THREAD

**Issue by Jpivot** [dromara/transaction-book#6]
除了第二点说到的，是不是也会有这样的情况：资源管理器收到了commit的消息，但是部分资源管理器commit失败了，导致数据不一致

**Comment by binghe001** [comment]
> 
> 
> 除了第二点说到的，是不是也会有这样的情况：资源管理器收到了commit的消息，但是部分资源管理器commit失败了，导致数据不一致

理论上这种情况也存在。不过本地事务commit失败的概率引起的不一致比网络抖动引起的不一致的概率低的多，同时，我们往往在实际实现基于2pc的事务框架时，第一阶段执行成功，第二阶段部分commit失败时，通常会进行重试，当重试达到一定次数，此时可以人工干预

**Comment by Jpivot** [comment]
> > 除了第二点说到的，是不是也会有这样的情况：资源管理器收到了commit的消息，但是部分资源管理器commit失败了，导致数据不一致
> 
> 理论上这种情况也存在。不过本地事务commit失败的概率引起的不一致比网络抖动引起的不一致的概率低的多，同时，我们往往在实际实现基于2pc的事务框架时，第一阶段执行成功，第二阶段部分commit失败时，通常会进行重试，当重试达到一定次数，此时可以人工干预

好的。谢谢解答
