### ISSUE TITLE
p49 p80印刷错误

### ISSUE THREAD

**Issue by Jpivot** [dromara/transaction-book#7]
p49 2）资源管理器：主要提供对对事务资源.......印刷多了一个“对”字
p80 3.6.4 同一类中的两个方法A和B上均添加了事务注解，方法A调用方法B。但是下面例子和解释却是A（submitOrder方法）没有加事务注解，虽然最终事务也是失效的（this.这种方式的调用，不是代理对象的调用），但上下文描述冲突了。

**Comment by binghe001** [comment]
> 
> 
> p49 2）资源管理器：主要提供对对事务资源.......印刷多了一个“对”字 p80 3.6.4 同一类中的两个方法A和B上均添加了事务注解，方法A调用方法B。但是下面例子和解释却是A（submitOrder方法）没有加事务注解，虽然最终事务也是失效的（this.这种方式的调用，不是代理对象的调用），但上下文描述冲突了。

谢谢反馈，这里的描述确实有误

**Comment by binghe001** [comment]
> 
> 
> p49 2）资源管理器：主要提供对对事务资源.......印刷多了一个“对”字 p80 3.6.4 同一类中的两个方法A和B上均添加了事务注解，方法A调用方法B。但是下面例子和解释却是A（submitOrder方法）没有加事务注解，虽然最终事务也是失效的（this.这种方式的调用，不是代理对象的调用），但上下文描述冲突了。


谢谢反馈，加印版已经更正
