### ISSUE TITLE
p106 p134 p150 p153 p155 p159印刷错误与提问

### ISSUE THREAD

**Issue by Jpivot** [dromara/transaction-book#8]
p106 由图6-8可以看出。。。事务管理器接收到doCommit（这里应该为“资源管理器”）
p134 5）下，有两段一模一样的“事务管理器在commit_send阶段宕机，可能会有。。。”
p150 优缺点 1）使用。。在多个服务之前传递消息数据（之“前”应该改为之“间”）
p153 10.4.1 实现原理，该标题往下数第4行，RockertMQ提供的（RockertMQ中间多了个“r”）
p155 代码片段中的注释，// transactionListene表示发送准备消息。。。（transactionListene单词拼写错误，末尾要加个“r”）
p159 10.6.2 消息接收的不一致性 3）会再次向事务发起方重试投递消息（这里应该为再次向“事务参与方”）

问题：
p140 9.2.2，try或confirm执行异常，tcc事务管理器可以自动感知，怎么自动感知和调用cancel？后续原理上没说，能否补充解释下。

**Comment by binghe001** [comment]
> 行异常，tcc事务管理器可以自动感知，怎么自动感知和调

首先，感谢反馈的印刷错误问题。   对于tcc事务管理器自动感知的机制，后面我会单独写一篇文章详细给大家介绍下

**Comment by Jpivot** [comment]
期待ing

**Comment by binghe001** [comment]
> 
> 
> p106 由图6-8可以看出。。。事务管理器接收到doCommit（这里应该为“资源管理器”） p134 5）下，有两段一模一样的“事务管理器在commit_send阶段宕机，可能会有。。。” p150 优缺点 1）使用。。在多个服务之前传递消息数据（之“前”应该改为之“间”） p153 10.4.1 实现原理，该标题往下数第4行，RockertMQ提供的（RockertMQ中间多了个“r”） p155 代码片段中的注释，// transactionListene表示发送准备消息。。。（transactionListene单词拼写错误，末尾要加个“r”） p159 10.6.2 消息接收的不一致性 3）会再次向事务发起方重试投递消息（这里应该为再次向“事务参与方”）
> 
> 问题： p140 9.2.2，try或confirm执行异常，tcc事务管理器可以自动感知，怎么自动感知和调用cancel？后续原理上没说，能否补充解释下。


谢谢反馈，加印版已经更正
